image: circleci/node:8-browsers

cache:
  paths:
  - node_modules/

test:
  stage: test
  script:
    - npm install
    - npm test
  artifacts:
    expire_in: 2 week
    when: always
    paths:
      - test_report/
  tags:
    - docker


